-- Create post_categories table
CREATE TABLE IF NOT EXISTS post_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE
);

-- Add category_id to posts table
ALTER TABLE posts ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES post_categories(id);

-- Enable RLS for post_categories
ALTER TABLE post_categories ENABLE ROW LEVEL SECURITY;

-- Policies for post_categories
CREATE POLICY "Allow public read categories" ON post_categories FOR SELECT USING (true);
CREATE POLICY "Allow authenticated manage categories" ON post_categories 
FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Update existing policies for posts to allow authenticated management if needed
-- (Usually handled by master_setup.sql, but ensuring here)
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'posts' AND policyname = 'Allow authenticated manage posts'
    ) THEN
        CREATE POLICY "Allow authenticated manage posts" ON posts 
        FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
END $$;
