-- 1. Create junction table for many-to-many relationship
CREATE TABLE IF NOT EXISTS post_categories_rel (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES post_categories(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(post_id, category_id)
);

-- 2. Enable RLS
ALTER TABLE post_categories_rel ENABLE ROW LEVEL SECURITY;

-- 3. Policies
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'post_categories_rel' AND policyname = 'Allow public read post relations'
    ) THEN
        CREATE POLICY "Allow public read post relations" ON post_categories_rel FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'post_categories_rel' AND policyname = 'Allow authenticated manage post relations'
    ) THEN
        CREATE POLICY "Allow authenticated manage post relations" ON post_categories_rel 
        FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
END $$;

-- 4. Migrate existing data from posts.category_id to post_categories_rel
INSERT INTO post_categories_rel (post_id, category_id)
SELECT id, category_id 
FROM posts 
WHERE category_id IS NOT NULL
ON CONFLICT (post_id, category_id) DO NOTHING;
