-- Tabela de Mandatos (Biênios/Triênios)
CREATE TABLE IF NOT EXISTS public.conselho_mandatos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,          -- Ex: "Biênio 2025-2026"
    ano_inicio INTEGER NOT NULL,
    ano_fim INTEGER NOT NULL,
    ativo BOOLEAN DEFAULT false,   -- Define qual é o mandato atual exibido por padrão
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de Membros do Conselho
CREATE TABLE IF NOT EXISTS public.conselho_membros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mandato_id BIGINT REFERENCES public.conselho_mandatos(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    cargo TEXT NOT NULL,           -- Ex: "Presidente", "Conselheiro Fiscal"
    foto_url TEXT,
    categoria TEXT NOT NULL,       -- 'presidencia', 'fiscal'
    ordem INTEGER DEFAULT 0,       -- Para ordenação na visualização
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies
ALTER TABLE public.conselho_mandatos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conselho_membros ENABLE ROW LEVEL SECURITY;

-- Public Access
CREATE POLICY "Public can view mandatos" ON public.conselho_mandatos FOR SELECT USING (true);
CREATE POLICY "Public can view membros" ON public.conselho_membros FOR SELECT USING (true);

-- Admin Access
CREATE POLICY "Admins can insert mandatos" ON public.conselho_mandatos FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Admins can update mandatos" ON public.conselho_mandatos FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Admins can delete mandatos" ON public.conselho_mandatos FOR DELETE TO authenticated USING (true);

CREATE POLICY "Admins can insert membros" ON public.conselho_membros FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Admins can update membros" ON public.conselho_membros FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Admins can delete membros" ON public.conselho_membros FOR DELETE TO authenticated USING (true);

-- Index for performance
CREATE INDEX IF NOT EXISTS idx_conselho_membros_mandato ON public.conselho_membros(mandato_id);
