-- Create table for Festa do Rei Jesus editions
CREATE TABLE IF NOT EXISTS public.festa_rei_jesus_editions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ano INTEGER NOT NULL UNIQUE,
    tema TEXT NOT NULL,
    descricao TEXT,
    imagem_url TEXT,
    local TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.festa_rei_jesus_editions ENABLE ROW LEVEL SECURITY;

-- Create policies
-- Allow public read access
CREATE POLICY "Public can view editions" 
ON public.festa_rei_jesus_editions FOR SELECT 
USING (true);

-- Allow admins to insert, update, delete (using the same logic as other tables, assuming authenticated users are admins for simplicity based on previous context, or strictly checking for role if implemented)
-- For now, we'll use the authenticated role check which is common in this project's context for "admin" actions if precise roles aren't fully set up, or just allow all authenticated for simplicity as requested often.
-- Ideally:
CREATE POLICY "Admins can insert editions" 
ON public.festa_rei_jesus_editions FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Admins can update editions" 
ON public.festa_rei_jesus_editions FOR UPDATE 
TO authenticated 
USING (true);

CREATE POLICY "Admins can delete editions" 
ON public.festa_rei_jesus_editions FOR DELETE 
TO authenticated 
USING (true);

-- Notify user
DO $$
BEGIN
    RAISE NOTICE 'Table festa_rei_jesus_editions created successfully.';
END $$;
