-- Calendário Diocesano da RCC
CREATE TABLE IF NOT EXISTS public.calendario_diocesano (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE,
    mes INTEGER NOT NULL,           -- 1-12 para facilitar filtros
    ano INTEGER NOT NULL DEFAULT 2026,
    categoria TEXT DEFAULT 'diocesano',  -- diocesano, estadual, nacional
    descricao TEXT,
    cor TEXT DEFAULT '#1e3a5f',      -- cor de acento para visual
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.calendario_diocesano ENABLE ROW LEVEL SECURITY;

-- Public read access
CREATE POLICY "Public can view calendario"
ON public.calendario_diocesano FOR SELECT
USING (true);

-- Admin insert/update/delete
CREATE POLICY "Admins can insert calendario"
ON public.calendario_diocesano FOR INSERT
TO authenticated WITH CHECK (true);

CREATE POLICY "Admins can update calendario"
ON public.calendario_diocesano FOR UPDATE
TO authenticated USING (true);

CREATE POLICY "Admins can delete calendario"
ON public.calendario_diocesano FOR DELETE
TO authenticated USING (true);

DO $$
BEGIN
    RAISE NOTICE 'Table calendario_diocesano created successfully.';
END $$;
