-- Tabela de Ministérios
CREATE TABLE IF NOT EXISTS public.ministerios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    descricao TEXT,
    coordenador TEXT,
    bienio TEXT,              -- Ex: "2025-2026"
    imagem_url TEXT,          -- URL para foto do coordenador ou do ministério
    cor TEXT DEFAULT 'bg-blue-100 text-blue-600',
    ordem INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies
ALTER TABLE public.ministerios ENABLE ROW LEVEL SECURITY;

-- Public Access
CREATE POLICY "Public can view ministerios" ON public.ministerios FOR SELECT USING (true);

-- Admin Access
CREATE POLICY "Admins can insert ministerios" ON public.ministerios FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Admins can update ministerios" ON public.ministerios FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Admins can delete ministerios" ON public.ministerios FOR DELETE TO authenticated USING (true);
