
-- 1. Create table safely (already done, but good to have)
CREATE TABLE IF NOT EXISTS public.festa_rei_jesus_editions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ano INTEGER NOT NULL UNIQUE,
    tema TEXT NOT NULL,
    descricao TEXT,
    imagem_url TEXT,
    local TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable RLS
ALTER TABLE public.festa_rei_jesus_editions ENABLE ROW LEVEL SECURITY;

-- 3. Drop existing policies to avoid "already exists" error
DROP POLICY IF EXISTS "Public can view editions" ON public.festa_rei_jesus_editions;
DROP POLICY IF EXISTS "Admins can insert editions" ON public.festa_rei_jesus_editions;
DROP POLICY IF EXISTS "Admins can update editions" ON public.festa_rei_jesus_editions;
DROP POLICY IF EXISTS "Admins can delete editions" ON public.festa_rei_jesus_editions;

-- 4. Re-create policies

-- Allow public read access
CREATE POLICY "Public can view editions" 
ON public.festa_rei_jesus_editions FOR SELECT 
USING (true);

-- Allow admins to insert/update/delete (authenticated users)
CREATE POLICY "Admins can insert editions" 
ON public.festa_rei_jesus_editions FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Admins can update editions" 
ON public.festa_rei_jesus_editions FOR UPDATE 
TO authenticated 
USING (true);

CREATE POLICY "Admins can delete editions" 
ON public.festa_rei_jesus_editions FOR DELETE 
TO authenticated 
USING (true);
