-- MASTER DATABASE SETUP: Grupo Rainha da Paz
-- Projeto ID: xxewcdrlcwalnrdlesmd

--------------------------------------------------------------------------------
-- 1. TABELAS CORE
--------------------------------------------------------------------------------

-- Site Settings (Configurações Dinâmicas)
CREATE TABLE IF NOT EXISTS public.site_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Posts (Blog / Notícias)
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGSERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    excerpt TEXT,
    image_url TEXT,
    category TEXT,
    author TEXT,
    slug TEXT UNIQUE,
    date TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Events (Agenda)
CREATE TABLE IF NOT EXISTS public.events (
    id BIGSERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    date DATE NOT NULL,
    time TEXT NOT NULL,
    location TEXT NOT NULL,
    category TEXT NOT NULL,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Prayer Requests (Pedidos de Oração)
CREATE TABLE IF NOT EXISTS public.prayer_requests (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Gallery (Fotos)
CREATE TABLE IF NOT EXISTS public.gallery (
    id BIGSERIAL PRIMARY KEY,
    title TEXT,
    image_url TEXT,
    category TEXT,
    event_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Groups (Grupos de Oração)
CREATE TABLE IF NOT EXISTS public.groups (
    id BIGSERIAL PRIMARY KEY,
    nome TEXT NOT NULL,
    dia TEXT,
    local TEXT,
    cidade TEXT NOT NULL,
    geolocalizacao TEXT,
    coordenador TEXT,
    whatsapp TEXT,
    site TEXT,
    facebook TEXT,
    instagram TEXT,
    slug TEXT UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Calendário (Interno/Diocesano)
CREATE TABLE IF NOT EXISTS public.calendario_diocesano (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE,
    mes INTEGER NOT NULL,
    ano INTEGER NOT NULL,
    categoria TEXT NOT NULL, -- 'diocesano', 'estadual', 'nacional'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Conselho Mandatos
CREATE TABLE IF NOT EXISTS public.conselho_mandatos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo TEXT NOT NULL,
    ano_inicio INTEGER NOT NULL,
    ano_fim INTEGER NOT NULL,
    ativo BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Conselho Membros
CREATE TABLE IF NOT EXISTS public.conselho_membros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mandato_id BIGINT REFERENCES public.conselho_mandatos(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    cargo TEXT NOT NULL,
    foto_url TEXT,
    categoria TEXT NOT NULL, -- 'presidencia', 'fiscal'
    ordem INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ministérios
CREATE TABLE IF NOT EXISTS public.ministerios (
    id BIGSERIAL PRIMARY KEY,
    nome TEXT NOT NULL,
    descricao TEXT,
    cor TEXT,
    ordem INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

--------------------------------------------------------------------------------
-- 2. STORAGE (BUCKETS)
--------------------------------------------------------------------------------
-- Nota: Rodar isso no SQL editor do Supabase cria os buckets se eles não existirem
INSERT INTO storage.buckets (id, name, public) 
VALUES ('media', 'media', true), ('galeria-fotos', 'galeria-fotos', true)
ON CONFLICT (id) DO UPDATE SET public = true;

--------------------------------------------------------------------------------
-- 3. RLS - SEGURANÇA (GERAL PARA ADMIN)
--------------------------------------------------------------------------------

-- Habilitar RLS em tudo
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prayer_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendario_diocesano ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conselho_mandatos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conselho_membros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ministerios ENABLE ROW LEVEL SECURITY;

-- Políticas de Leitura Pública
CREATE POLICY "Public Read Settings" ON public.site_settings FOR SELECT USING (true);
CREATE POLICY "Public Read Posts" ON public.posts FOR SELECT USING (true);
CREATE POLICY "Public Read Events" ON public.events FOR SELECT USING (true);
CREATE POLICY "Public Read Gallery" ON public.gallery FOR SELECT USING (true);
CREATE POLICY "Public Read Groups" ON public.groups FOR SELECT USING (true);
CREATE POLICY "Public Read Calendario" ON public.calendario_diocesano FOR SELECT USING (true);
CREATE POLICY "Public Read Mandatos" ON public.conselho_mandatos FOR SELECT USING (true);
CREATE POLICY "Public Read Membros" ON public.conselho_membros FOR SELECT USING (true);
CREATE POLICY "Public Read Ministerios" ON public.ministerios FOR SELECT USING (true);

-- Política de Inserção Pública (Pedidos de Oração)
CREATE POLICY "Public Insert Prayer" ON public.prayer_requests FOR INSERT WITH CHECK (true);

-- Acesso Total para Autenticados (Admin)
CREATE POLICY "Admin Full Access Settings" ON public.site_settings FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin Full Access Posts" ON public.posts FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin Full Access Events" ON public.events FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin Full Access Prayer" ON public.prayer_requests FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin Full Access Gallery" ON public.gallery FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin Full Access Groups" ON public.groups FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin Full Access Calendario" ON public.calendario_diocesano FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin Full Access Mandatos" ON public.conselho_mandatos FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin Full Access Membros" ON public.conselho_membros FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin Full Access Ministerios" ON public.ministerios FOR ALL USING (auth.role() = 'authenticated');

-- Políticas de Storage
CREATE POLICY "Public View Media" ON storage.objects FOR SELECT USING (bucket_id IN ('media', 'galeria-fotos'));
CREATE POLICY "Admin Manage Media" ON storage.objects FOR ALL TO authenticated USING (bucket_id IN ('media', 'galeria-fotos'));

--------------------------------------------------------------------------------
-- 4. SEED - DADOS INICIAIS (REBRANDED)
--------------------------------------------------------------------------------

-- Events (Agenda 2026)
INSERT INTO public.events (title, description, date, time, location, category) VALUES
('Início do Seminário de Vida Rainha da Paz', 'Início da nossa caminhada de 8 semanas de Seminário de Vida no Espírito Santo.', '2026-03-07', '19:30', 'Matriz da Paróquia Santo Antônio', 'Seminário'),
('Encerramento do Seminário de Vida Rainha da Paz', 'Grande encerramento do Seminário de Vida no Espírito Santo.', '2026-04-25', '19:30', 'Matriz da Paróquia Santo Antônio', 'Seminário'),
('Experiência de Oração Rainha da Paz (Dia 1)', 'Um final de semana de profunda imersão e oração.', '2026-05-09', '13:30', 'Matriz da Paróquia Santo Antônio', 'Retiro'),
('Experiência de Oração Rainha da Paz (Dia 2)', 'Continuação da nossa Experiência de Oração.', '2026-05-10', '07:30', 'Matriz da Paróquia Santo Antônio', 'Retiro'),
('Formação Básica: Apostila 1 (Sáb)', 'Módulo Básico de Formação da RCC.', '2026-06-13', '13:30', 'Matriz da Paróquia Santo Antônio', 'Formação'),
('Formação Básica: Apostila 1 (Dom)', 'Módulo Básico de Formação da RCC.', '2026-06-14', '07:30', 'Matriz da Paróquia Santo Antônio', 'Formação'),
('Formação Básica: Apostila 2 (Sáb)', 'Continuação dos estudos do Módulo Básico.', '2026-06-27', '13:30', 'Matriz da Paróquia Santo Antônio', 'Formação'),
('Formação Básica: Apostila 2 (Dom)', 'Continuação dos estudos do Módulo Básico.', '2026-06-28', '07:30', 'Matriz da Paróquia Santo Antônio', 'Formação'),
('Formação Básica: Apostila 3 (Sáb)', 'Aprofundamento na doutrina e identidade da RCC.', '2026-07-11', '13:30', 'Matriz da Paróquia Santo Antônio', 'Formação'),
('Formação Básica: Apostila 3 (Dom)', 'Aprofundamento na doutrina e identidade da RCC.', '2026-07-12', '07:30', 'Matriz da Paróquia Santo Antônio', 'Formação'),
('Formação Básica: Apostila 4 (Sáb)', 'Formação para servos e ministérios.', '2026-08-01', '13:30', 'Matriz da Paróquia Santo Antônio', 'Formação'),
('Formação Básica: Apostila 4 (Dom)', 'Formação para servos e ministérios.', '2026-08-02', '07:30', 'Matriz da Paróquia Santo Antônio', 'Formação'),
('Formação Básica: Apostila 5 (Sáb)', 'Estudos bíblicos e carismas.', '2026-09-19', '13:30', 'Matriz da Paróquia Santo Antônio', 'Formação'),
('Formação Básica: Apostila 5 (Dom)', 'Estudos bíblicos e carismas.', '2026-09-20', '07:30', 'Matriz da Paróquia Santo Antônio', 'Formação'),
('Formação Básica: Apostila 6 (Sáb)', 'Liderança e serviço na Igreja.', '2026-10-24', '13:30', 'Matriz da Paróquia Santo Antônio', 'Formação'),
('Formação Básica: Apostila 6 (Dom)', 'Liderança e serviço na Igreja.', '2026-10-25', '07:30', 'Matriz da Paróquia Santo Antônio', 'Formação'),
('Formação Básica: Apostila 7 (Sáb)', 'Vida comunitária e missão.', '2026-11-07', '13:30', 'Matriz da Paróquia Santo Antônio', 'Formação'),
('Formação Básica: Apostila 7 (Dom)', 'Vida comunitária e missão.', '2026-11-08', '07:30', 'Matriz da Paróquia Santo Antônio', 'Formação'),
('Formação Básica: Apostila 8 (Sáb)', 'Encerramento do Módulo Básico.', '2026-12-05', '13:30', 'Matriz da Paróquia Santo Antônio', 'Formação'),
('Formação Básica: Apostila 8 (Dom)', 'Encerramento do Módulo Básico.', '2026-12-06', '07:30', 'Matriz da Paróquia Santo Antônio', 'Formação'),
('Início do Recesso 2026', 'Encerramento das atividades anuais do Grupo de Oração.', '2026-12-16', '19:30', 'Matriz da Paróquia Santo Antônio', 'Aviso')
ON CONFLICT DO NOTHING;

-- Home Banner
INSERT INTO public.site_settings (key, value)
VALUES (
    'home_banner',
    '{
        "title": "Grupo Rainha da Paz",
        "subtitle": "Um encontro de amor com o Espírito Santo em Sinop.",
        "image_url": "https://images.unsplash.com/photo-1544427920-c49ccfb85579?q=80&w=2000&auto=format&fit=crop",
        "button1_text": "Conheça nossa História",
        "button1_link": "/quem-somos",
        "button2_text": "Pedido de Oração",
        "button2_link": "/contato#pedido-oracao"
    }'::jsonb
) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Quem Somos
INSERT INTO public.site_settings (key, value)
VALUES (
    'about_us',
    '{
        "hero": {
            "title": "Quem Somos",
            "subtitle": "Conheça a história, a missão e os valores que movem o Grupo Rainha da Paz.",
            "image_url": "https://images.unsplash.com/photo-1510915228340-29c85a43dbfe?q=80&w=2000"
        },
        "history": {
            "p1": "O Grupo de Oração Rainha da Paz nasceu do desejo profundo de buscar uma experiência viva com o Espírito Santo, reunindo-se na Matriz da Paróquia Santo Antônio em Sinop.",
            "p2": "Movidos pelo compromisso com a Renovação Carismática Católica, somos uma expressão de fé que busca o Batismo no Espírito Santo, a cura interior e o crescimento na vida espiritual de todo o povo de Deus.",
            "p3": "Hoje, somos uma grande família reunida pelo amor de Maria e pela força de um novo Pentecostes.",
            "title": "Uma Caminhada de Fé e Adoração",
            "quote": "A Renovação Carismática Católica é um grande dom do Espírito Santo à Igreja e ao mundo.",
            "image_url": "https://images.unsplash.com/photo-1544427920-c49ccfb85579?q=80&w=1000"
        }
    }'::jsonb
) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Groups Page
INSERT INTO public.site_settings (key, value)
VALUES (
    'groups_page',
    '{
        "title": "Grupos de Oração",
        "subtitle": "Encontre um Grupo de Oração Rainha da Paz mais próximo de você e venha vivenciar Pentecostes!",
        "image_url": "https://images.unsplash.com/photo-1544427920-c49ccfb85579?q=80&w=2000&auto=format&fit=crop"
    }'::jsonb
) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Ministérios
INSERT INTO public.ministerios (nome, descricao, cor, ordem) VALUES
('Ministério de Pregação', 'Anunciando a Palavra com poder.', 'bg-blue-100 text-blue-600', 1),
('Oração por Cura e Libertação', 'Intercessão pela cura integral.', 'bg-red-100 text-red-600', 2),
('Ministério Jovem', 'Sentinelas da Manhã.', 'bg-orange-100 text-orange-600', 4),
('Ministério de Intercessão', 'A base de toda a missão.', 'bg-purple-100 text-purple-600', 6)
ON CONFLICT DO NOTHING;

-- Grupos Seed (Exemplo)
INSERT INTO public.groups (nome, dia, local, cidade, coordenador, whatsapp, slug)
VALUES 
('Rainha da Paz', 'Quarta-feira, às 19:30', 'Paróquia Santo Antônio', 'Sinop', 'Gelson Pandolfo', 'https://wa.me/556681365456', 'rainha-da-paz')
ON CONFLICT (slug) DO NOTHING;
