-- Consolidação da Festa do Rei Jesus
-- 1. Criar tabela de edições se não existir
CREATE TABLE IF NOT EXISTS public.festa_rei_jesus_editions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ano INTEGER NOT NULL UNIQUE,
    tema TEXT NOT NULL,
    descricao TEXT,
    imagem_url TEXT,
    local TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Garantir colunas extras (datas e atrações)
ALTER TABLE public.festa_rei_jesus_editions ADD COLUMN IF NOT EXISTS data_inicio DATE;
ALTER TABLE public.festa_rei_jesus_editions ADD COLUMN IF NOT EXISTS data_fim DATE;
ALTER TABLE public.festa_rei_jesus_editions ADD COLUMN IF NOT EXISTS atracoes JSONB DEFAULT '[]'::jsonb;

-- Habilitar RLS
ALTER TABLE public.festa_rei_jesus_editions ENABLE ROW LEVEL SECURITY;

-- Criar políticas se não existirem
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public can view editions' AND tablename = 'festa_rei_jesus_editions') THEN
        CREATE POLICY "Public can view editions" ON public.festa_rei_jesus_editions FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admins can insert editions' AND tablename = 'festa_rei_jesus_editions') THEN
        CREATE POLICY "Admins can insert editions" ON public.festa_rei_jesus_editions FOR INSERT TO authenticated WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admins can update editions' AND tablename = 'festa_rei_jesus_editions') THEN
        CREATE POLICY "Admins can update editions" ON public.festa_rei_jesus_editions FOR UPDATE TO authenticated USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admins can delete editions' AND tablename = 'festa_rei_jesus_editions') THEN
        CREATE POLICY "Admins can delete editions" ON public.festa_rei_jesus_editions FOR DELETE TO authenticated USING (true);
    END IF;
END $$;

-- 2. Criar tabela de páginas customizadas se não existir
CREATE TABLE IF NOT EXISTS public.custom_pages (
    id BIGSERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    content TEXT NOT NULL,
    parent_menu TEXT DEFAULT 'quem-somos',
    is_published BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS para custom_pages
ALTER TABLE public.custom_pages ENABLE ROW LEVEL SECURITY;

-- Criar políticas para custom_pages se não existirem
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read-only access on custom_pages' AND tablename = 'custom_pages') THEN
        CREATE POLICY "Allow public read-only access on custom_pages" ON public.custom_pages FOR SELECT TO public USING (is_published = true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow authenticated full access on custom_pages' AND tablename = 'custom_pages') THEN
        CREATE POLICY "Allow authenticated full access on custom_pages" ON public.custom_pages FOR ALL TO authenticated USING (true) WITH CHECK (true);
    END IF;
END $$;

-- 3. Inserir/Atualizar Edição 2026
INSERT INTO public.festa_rei_jesus_editions (ano, tema, descricao, imagem_url, local, data_inicio, data_fim)
VALUES (
    2026,
    'Um evento para fortalecer sua fé e renovar sua esperança!',
    'A Festa do Rei Jesus é um dos momentos mais aguardados pela família carismática da Diocese de Sinop. São dois dias de profunda imersão no amor de Deus, com muito louvor, adoração, pregações ungidas e a Santa Missa, o ápice da nossa fé. É uma oportunidade única para você e sua família renovarem as forças e a esperança em Cristo Jesus, nosso único Senhor e Rei!',
    'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?ixlib=rb-1.2.1&auto=format&fit=crop&w=1920&q=80',
    'Paróquia São Cristóvão, Sinop - MT',
    '2026-11-21',
    '2026-11-22'
) ON CONFLICT (ano) DO UPDATE SET
    tema = EXCLUDED.tema,
    descricao = EXCLUDED.descricao,
    imagem_url = EXCLUDED.imagem_url,
    local = EXCLUDED.local,
    data_inicio = EXCLUDED.data_inicio,
    data_fim = EXCLUDED.data_fim;

-- 4. Atualizar o conteúdo "Sobre o Evento" em custom_pages
INSERT INTO public.custom_pages (title, slug, content, parent_menu, is_published)
VALUES (
    'Festa do Rei Jesus',
    'festa-rei-jesus',
    '<p>A Festa do Rei Jesus é um dos momentos mais aguardados pela família carismática da Diocese de Sinop. São dois dias de profunda imersão no amor de Deus, com muito louvor, adoração, pregações ungidas e a Santa Missa, o ápice da nossa fé.</p><p>É uma oportunidade única para você e sua família renovarem as forças e a esperança em Cristo Jesus, nosso único Senhor e Rei!</p>',
    'Eventos',
    true
) ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    parent_menu = EXCLUDED.parent_menu,
    is_published = EXCLUDED.is_published;
