-- Create site_settings table if not exists
CREATE TABLE IF NOT EXISTS public.site_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Policies
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read' AND tablename = 'site_settings') THEN
        CREATE POLICY "Allow public read" ON public.site_settings FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow authenticated full access' AND tablename = 'site_settings') THEN
        CREATE POLICY "Allow authenticated full access" ON public.site_settings FOR ALL USING (auth.role() = 'authenticated');
    END IF;
END $$;
-- Create groups table if not exists
CREATE TABLE IF NOT EXISTS public.groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    dia TEXT,
    local TEXT,
    cidade TEXT NOT NULL,
    geolocalizacao TEXT,
    coordenador TEXT,
    whatsapp TEXT,
    site TEXT,
    facebook TEXT,
    instagram TEXT,
    slug TEXT UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for groups
ALTER TABLE public.groups ENABLE ROW LEVEL SECURITY;

-- Policies for groups
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read' AND tablename = 'groups') THEN
        CREATE POLICY "Allow public read" ON public.groups FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow authenticated full access' AND tablename = 'groups') THEN
        CREATE POLICY "Allow authenticated full access" ON public.groups FOR ALL USING (auth.role() = 'authenticated');
    END IF;
END $$;

-- Limpar grupos existentes (opcional, dependendo da necessidade de resetar)
DELETE FROM public.groups;

-- Inserir os 31 grupos extraídos do site legado
INSERT INTO public.groups (nome, dia, local, cidade, coordenador, whatsapp, slug)
VALUES 
('Sagrado Coração de Jesus', 'Segunda, às 19:30', 'Catedral Sagrado Coração de Jesus', 'Sinop', NULL, NULL, 'sagrado-coracao-de-jesus'),
('Nossa Senhora das Graças', 'Segunda, às 19:00', 'Capela Nossa Senhora de Fátima', 'Sinop', NULL, NULL, 'nossa-senhora-das-gracas'),
('Rainha da Paz', 'Quarta-feira, às 19:30', 'Paróquia Santo Antônio', 'Sinop', 'Gelson Pandolfo', 'https://wa.me/556681365456', 'rainha-da-paz'),
('São Cristóvão', 'Quarta, às 19:30', 'Paróquia São Cristóvão', 'Sinop', NULL, NULL, 'sao-cristovao'),
('Nossa Senhora Aparecida', 'Quinta, às 19:30', 'Comunidade N. Sra. Aparecida', 'Sinop', NULL, NULL, 'nossa-senhora-aparecida'),
('Santa Clara', 'Quinta, às 19:30', 'Paróquia Todos os Santos', 'Sinop', NULL, NULL, 'santa-clara'),
('Cristo Rei', 'Quinta, às 19:30', 'Paróquia São Camilo', 'Sinop', NULL, NULL, 'cristo-rei'),
('São Miguel Arcanjo', 'Terça, às 19:30', 'Comunidade Divino Pai Eterno', 'Cláudia', NULL, NULL, 'sao-miguel-arcanjo'),
('Divina Luz', 'Terça, às 19:00', 'Paróquia Cristo Rei', 'União do Sul', NULL, NULL, 'divina-luz'),
('Imaculado Coração de Maria', 'Terça, às 19:30', 'Salão da Comunidade', 'Gleba Mercedes (BR-080)', NULL, NULL, 'imaculado-coracao-de-maria'),
('Chama de Amor', 'Terça, às 19:30', 'Paróquia Sagrado Coração de Jesus', 'Vera', NULL, NULL, 'chama-de-amor'),
('Anjos da Luz', 'Quarta, às 19:30', 'Comunidade N. Sra. do Perpétuo Socorro', 'Vera', NULL, NULL, 'anjos-da-luz'),
('Caminhando com Cristo', 'Quinta, às 19:30', 'Salão Paroquial', 'Feliz Natal', NULL, NULL, 'caminhando-com-cristo'),
('São Rafael', 'Terça, às 19:00', 'Salão Paroquial', 'Santa Carmem', NULL, NULL, 'sao-rafael'),
('Bom Pastor', 'Segunda, às 19:00', 'Paróquia N. Sra. da Consolata', 'Sorriso', NULL, NULL, 'bom-pastor'),
('Anuncia-me', 'Terça, às 19:30', 'Paróquia São Pedro Apóstolo', 'Sorriso', NULL, NULL, 'anuncia-me'),
('O Bom Samaritano', 'Quarta, às 19:30', 'Paróquia São José', 'Juara', NULL, NULL, 'o-bom-samaritano'),
('Sagrada Família', 'Quinta, às 19:30', 'Paróquia N. Sra. Aparecida', 'Porto dos Gaúchos', NULL, NULL, 'sagrada-familia'),
('N. Sra. de Fátima', 'Terça, às 19:30', 'Paróquia N. Sra. de Fátima', 'Marcelândia', NULL, NULL, 'n-sra-de-fatima'),
('Filhos da Mãe da Misericórdia', 'Quarta, às 19:30', 'Salão Paroquial', 'Colíder', NULL, NULL, 'filhos-da-mae-da-misericordia'),
('Jesus Misericordioso', 'Quinta, às 19:00', 'Paróquia N. Sra. de Fátima', 'Itaúba', NULL, NULL, 'jesus-misericordioso'),
('Nova Aliança', 'Segunda, às 19:30', 'Paróquia N. Sra. Aparecida', 'Nova Santa Helena', NULL, NULL, 'nova-alianca'),
('Fonte de Luz', 'Quarta, às 19:30', 'Paróquia São Judas Tadeu', 'Guarantã do Norte', NULL, NULL, 'fonte-de-luz'),
('Beata Helena Guerra', 'Quarta, às 19:00', 'Paróquia N. Sra. da Guia', 'Nova Canaã do Norte', NULL, NULL, 'beata-helena-guerra'),
('Mergulho na Misericórdia Divina', 'Segunda, às 19:30', 'Paróquia N. Sra. Aparecida', 'Matupá', NULL, NULL, 'mergulho-na-misericordia-divina'),
('Adoração e Graça', 'Quarta, às 19:30', 'Paróquia N. Sra. Aparecida', 'Peixoto de Azevedo', NULL, NULL, 'adoracao-e-graca'),
('Incendeia', 'Quinta, às 19:30', 'Salão Paroquial', 'Alta Floresta', NULL, NULL, 'incendeia'),
('Chave Do Céu', 'Segunda, às 19:30', 'Paróquia N. Sra. da Salete', 'Novo Horizonte do Norte', NULL, NULL, 'chave-do-ceu'),
('Amigos de Jesus', 'Terça, às 19:30', 'Paróquia N. Sra. da Conceição', 'Apiacás', NULL, NULL, 'amigos-de-jesus'),
('São Padre Pio', 'Quarta, às 19:30', 'Salão da Comunidade', 'Nova Monte Verde', NULL, NULL, 'sao-padre-pio'),
('Renascer', 'Quinta, às 19:30', 'Paróquia Santo Agostinho', 'Paranaíta', NULL, NULL, 'renascer');

-- Adicionar configuração inicial da página de grupos
INSERT INTO public.site_settings (key, value)
VALUES (
    'groups_page',
    '{
        "title": "Grupos de Oração",
        "subtitle": "Encontre um Grupo de Oração Rainha da Paz mais próximo de você e venha vivenciar Pentecostes!",
        "image_url": "https://images.unsplash.com/photo-1544427920-c49ccfb85579?q=80&w=2000&auto=format&fit=crop"
    }'::jsonb
)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
